=== ringsce/ringsce-overlay/src/kayte/ui/UI.dtd
<!ELEMENT UI (Window+)>
<!ELEMENT Window (Title, Content)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Content (Map | MiniMap | AmmoCountChart | Buttons | ListView | Chart | Pie | ProgressBar)>
<!ELEMENT Map (AxisX, AxisY)>
<!ELEMENT MiniMap (AxisX, AxisY)>
<!ELEMENT AmmoCountChart (AxisX, AxisY)>
<!ELEMENT AxisX (#PCDATA)>
<!ELEMENT AxisY (#PCDATA)>
<!ELEMENT Buttons (#PCDATA)>
<!ELEMENT ListView (#PCDATA)>
<!ELEMENT Chart (#PCDATA)>
<!ELEMENT Pie (#PCDATA)>
<!ELEMENT ProgressBar (#PCDATA)>

=== ringsce/ringsce-overlay/src/kayte/ui/ui.xml
<!DOCTYPE UI SYSTEM "ui.dtd">
<UI>
  <Window>
    <Title>Welcome Window</Title>
    <Content>
      <Map>
        <AxisX>X Axis</AxisX>
        <AxisY>Y Axis</AxisY>
      </Map>
      <MiniMap>
        <AxisX>X Axis</AxisX>
        <AxisY>Y Axis</AxisY>
      </MiniMap>
      <AmmoCountChart>
        <AxisX>X Axis</AxisX>
        <AxisY>Y Axis</AxisY>
      </AmmoCountChart>
      <Buttons>Button 1</Buttons>
      <Buttons>Button 2</Buttons>
      <ListView>List Item 1</ListView>
      <ListView>List Item 2</ListView>
      <Chart>Chart Data</Chart>
      <Pie>Pie Data</Pie>
      <ProgressBar>50%</ProgressBar>
    </Content>
  </Window>
</UI>
